spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/test
    username: root
    password: root
    druid:
      filters: stat,wall,slf4j
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000 #慢查询
          log-slow-sql: true
        wall:
          enabled: true
          config:
            #update-allow: false #不允许更新
            drop-table-allow: false #不允许删表
            delete-allow: false #不允许删数据
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      stat-view-servlet:
        enabled: true
        login-username: zookao
        login-password: 111111
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      aop-patterns: com.zookao.boot.*
  mvc:
    #static-path-pattern: /static/** #会导致welcome page 如index.html失效
  web:
    resources:
      static-locations: [classpath:/static/]
  servlet:
    multipart:
      max-file-size: 100MB
  jdbc:
    template:
      query-timeout: 3
  aop:
    auto: false # 解决 spring监控 页面无数据的问题
server:
  port: 88
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always