spring :
  datasource :
    url : jdbc:mysql://localhost:3306/auth
    username : root
    password : zbxhDL13
    driverClassName : com.mysql.jdbc.Driver
mybatis :
  config-location : classpath:/mybatis-config.xml
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "